### PR TITLE
Less fatal find_ip

### LINKED ISSUE #3039: Avoid crashing the node process when determining our external IP.
My typical setup for nodes involves machines which set inbound and outbound firewall rules to drop all. I then whitelist ports and IP ranges as necessitated by the project and risk assessments. This includes outbound traffic as it can aid with host security.

I configured my firewall rules to allow port 8303 and 8302 (in and out) per the documentation. However, when I launched my node, it still crashed. This seems to have happened because it tried to talk to another node that was using ports other than the documented defaults.

It would be nice if my node did not crash when it tried and failed to talk to another node - instead simply moving on to connect to other peers.

```
coda daemon -peer hello-coda.o1test.net:8303


  ☠  Coda Daemon crashed. The Coda Protocol developers would like to know why!

  Please:
    Open an issue:
      https://github.com/CodaProtocol/coda/issues/new

    Briefly describe what you were doing, and include the last 20 lines from .coda-config/coda.log.
    And then paste the following:

    (monitor.ml.Error
  ("connection attempt timeout" 50.16.229.140:443 src/tcp.ml:120:11)
  ("Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30"
    "Called from file \"src/error.ml\" (inlined), line 5, characters 2-50"
    "Called from file \"src/tcp.ml\", line 120, characters 11-76"
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5"
    "Called from file \"src/job_queue.ml\", line 170, characters 6-47"
    "Caught by monitor coda"))
```

### PR DESCRIPTION
**Pull request by cmr**
This raises a better exception after failing to find our IP, and documents the error.

Closes #3039

### CODE REVIEW

File: src/app/cli/src/find_ip.ml [hunk 1]
```diff
@@ -10,16 +10,33 @@ let services =
...
+    Monitor.try_with (fun () ->
+        let%bind resp, body = Client.get (Uri.of_string uri) in
+        let%map body = Body.to_string body in
+        if resp.status = `OK then Some (body_handler body) else None )
+  with
+  | Ok v ->
+      v
+  | Error e ->
+      Logger.error logger ~module_:__MODULE__ ~location:__LOC__
+        "failed to query our own IP from $provider: $exn"
```
Comment (psteckler) [inline src/app/cli/src/find_ip.ml]: init-caps: `Failed`

File: src/app/cli/src/find_ip.ml [hunk 2]
```diff
@@ -10,16 +10,33 @@ let services =
...
+        return acc
   in
-  Deferred.List.fold services ~init:None ~f:handler
-  >>| fun x ->
+  let%map our_ip_maybe = Deferred.List.fold services ~init:None ~f:handler in
   Unix.Inet_addr.of_string
-  @@ Option.value_exn ~message:"couldn't determine our IP from the internet" x
+  @@ Option.value_exn
+       ~message:
+         "couldn't determine our IP from the internet, use -external-ip flag"
```
Comment (psteckler) [inline src/app/cli/src/find_ip.ml]: `Couldn't`

File: frontend/website/docs/getting-started.md [hunk 3]
```diff
@@ -55,9 +55,11 @@ Windows is not yet supported. If you have any interest in developing Coda for Wi
 
 If you're running another Linux distro or a different version of macOS, you can [try building Coda from source code](https://github.com/CodaProtocol/coda/blob/master/README-dev.md#building-coda). Please note that other operating systems haven't been tested thoroughly, and may have issues. Feel free to share any logs and get troubleshooting help in the Discord channel.
 
-## Set up port forwarding
+## Set up port forwarding and any firewalls
 
-You must allow inbound traffic to the following ports through your **external** IP address.
+If you are running a firewall, you should allow traffic on TCP port 8302 and UDP port 8303. Additionally, unless the `-external-ip YOUR_IP` flag is provided, the daemon will use HTTPS (443) and HTTP (80) to try and determine its own IP.
```
Comment (psteckler) [inline frontend/website/docs/getting-started.md]: miniscule nit: `its own IP address` (IP is the protocol).
