### PR TITLE
Fixes #5724 in develop

### LINKED ISSUE #5724: Creating a new token crashes the daemon
I am using the rosetta container to build a local network to test the new CLI. I am building off the https://github.com/CodaProtocol/coda/pull/5710 branch (it's now been merged.)

To start the network I'm running:
`coda/src/app/rosetta/start.sh CURL`

The daemon crashes when I issue:
`./coda.exe client create-token -sender $CODA_PUBLIC_KEY1`

[coda_crash_report_2020-08-20_22-45-51.056911.tar.gz](https://github.com/CodaProtocol/coda/files/5105837/coda_crash_report_2020-08-20_22-45-51.056911.tar.gz)

### PR DESCRIPTION
**Pull request by deepthiskumar**
1. delegate field to be empty for non-default tokens
2. pass correct `next_available_token` to the scan state `check_invariants` function

Checklist:

- [ ] Document code purpose, how to use it
  - Mention expected invariants, implicit constraints
- [ ] Tests were added for the new behavior
  - Document test purpose, significance of failures
  - Test names should reflect their purpose
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them:

### CODE REVIEW

File: src/lib/coda_base/sparse_ledger.ml [hunk 1]
```diff
@@ -134,9 +134,15 @@ let get_or_initialize_exn account_id t idx =
...
+    let token_id = Account_id.token_id account_id in
+    let delegate =
+      (* Only allow delegation if this account is for the default token. *)
+      if Token_id.(equal default) token_id then public_key
+      else Public_key.Compressed.empty
+    in
     ( `Added
     , { account with
-        delegate= public_key
+        delegate
```
Comment (psteckler) [inline src/lib/coda_base/sparse_ledger.ml:145]: It seems a bit funny to use the `empty` key to indicate no delegation.

Would it be better to use an option?

Comment (psteckler) [reply src/lib/coda_base/sparse_ledger.ml:145]: Actually, haven't we been using the account pk for the delegate in the case where there's no delegation?

Comment (deepthiskumar) [reply src/lib/coda_base/sparse_ledger.ml:144]: Yeah that's the default (all the accounts delegate to themselves?). But in the case of non-default tokens we don't want to allow delegation at all
