### PR TITLE
Check snarks before adding it to snark pool

### LINKED ISSUE #589: Snark pool not checking snarks
I may be wrong but it looks like we don't check snarks when putting them into the snark pool/rebroadcasting them. This is of course wrong. However, it is still a big DDOS channel (since someone can flood us with correct proofs of useless statements) so we need to figure out something there.

### PR DESCRIPTION
**Pull request by deepthiskumar**
Checklist:

- [X] Tests were added for the new behavior
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [X] Does this close issues? List them:

Closes #589

### CODE REVIEW

File: src/lib/network_pool/snark_pool.ml [hunk 1]
```diff
@@ -219,6 +223,57 @@ struct
...
+          | Ok true ->
+              Deferred.Or_error.return ()
+          | Ok false ->
+              (*Invalid proof*)
+              let e = Error.of_string "Invalid proof" in
+              let%map () = log_and_punish statement e in
+              Error e
+          | Error e ->
+              (*Other errors but punish for sending erroneous work*)
+              let%map () = log_and_punish statement e in
```
Comment (enolan) [inline src/lib/network_pool/snark_pool.ml]: The verification process can fail because the verifier process dies, and probably for other reasons that don't indicate the proof is invalid. We need to distinguish verification returning false from verification failing due to problems on our end. I have a PR for this in #3402, and Paul has been working on the worker processes in general.

File: src/lib/one_or_two/one_or_two.ml [hunk 2]
```diff
@@ -36,15 +36,18 @@ let group_sequence : 'a Sequence.t -> 'a t Sequence.t =
 let group_list : 'a list -> 'a t list =
  fun xs -> xs |> Sequence.of_list |> group_sequence |> Sequence.to_list
 
-let zip_exn : 'a t -> 'b t -> ('a * 'b) t =
+let zip : 'a t -> 'b t -> ('a * 'b) t Or_error.t =
```
Comment (enolan) [inline src/lib/one_or_two/one_or_two.ml]: :+1:

File: src/lib/staged_ledger/staged_ledger.ml [hunk 3]
```diff
@@ -73,7 +73,8 @@ module T = struct
           Logger.warn logger ~module_:__MODULE__ ~location:__LOC__
             ~metadata:
               [ ("statement", Transaction_snark.Statement.to_yojson statement)
-              ; ("error", `String (Error.to_string_hum e)) ]
+              ; ("error", `String (Error.to_string_hum e))
+              ; ("sok", Sok_message.to_yojson message) ]
```
Comment (enolan) [inline src/lib/staged_ledger/staged_ledger.ml]: should be "sok_message" or something. Just "sok" implies it's the signature.

File: src/lib/network_pool/snark_pool.ml [hunk 4]
```diff
@@ -219,6 +223,57 @@ struct
...
+              Error e
+        in
+        let%bind pairs = One_or_two.zip statements proofs |> Deferred.return in
```
Comment (psteckler) [inline src/lib/network_pool/snark_pool.ml]: Could you use a vanilla `let` here, without the `Deferred.return`?

Comment (deepthiskumar) [reply src/lib/network_pool/snark_pool.ml]: it is binding a `Deferred.Or_error`

**Comment by deepthiskumar** [comment]
> Why are we still verifying snarks in `Staged_ledger.ml` if we're verifying them before they go into the snark pool now?

Because snarks in blocks from peers need to be checked before accepting them. This does cause a block producer's snarks to be checked twice, once before adding it to the snark pool and again when `Internal_transition` turns in to an `External_transition` and added to the transition frontier

File: src/lib/network_pool/snark_pool_diff.ml [hunk 5]
```diff
@@ -87,11 +88,19 @@ end)
...
-            ~sender:(Envelope.Incoming.sender t)
+          let check () =
+            Pool.verify_and_act pool ~work:(work, p)
+              ~sender:(Envelope.Incoming.sender t)
+          in
+          match Pool.request_proof pool work with
+          | None ->
+              check ()
+          | Some {fee= {fee= prev; _}; _} ->
+              if Currency.Fee.( < ) prev fee.fee then
```
Comment (enolan) [inline src/lib/network_pool/snark_pool_diff.ml]: you want `<=`, we should use the first one we get at a given fee.

Comment (deepthiskumar) [reply src/lib/network_pool/snark_pool_diff.ml]: Oops. Thanks!

**Comment by bkase** [comment]
Landing because those files owned by people blocking on this are also owned by deepthi
