### PR TITLE
Fix metadata.peer in trust to differentiate from communications

### LINKED ISSUE #3418: [Bug] Overloaded Field metadata.peer within log output
Kibana has registered a conflict in our logs for the `metadata.peer` field. There are certain logs that present `metadata.peer` as a String and others that present it as an object, leading to this conflict. 

Screen Shot 2019-09-11 at 3 41 50 PM

Example Log JSON w/ String: 
```
{
  "_index": "filebeat-7.0.1-2019.09.11",
  "_type": "doc",
  "_id": "v2F_Im0BrQMp5MwOcEo5",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2019-09-11T22:43:59.183Z",
    "host": {
      "name": "golden-hour_us-west-2_seedjoiner_0.us-west-2"
    },
    "log": {
      "offset": 87837326,
      "file": {
        "path": "/home/admin/test-coda/coda.log"
      }
    },
    "timestamp": "2019-09-11 22:43:52.749496Z",
    "message": "Increasing trust for peer $peer due to action Trust_system.Actions.Sent_useful_gossip (external transition $state_hash). New trust is 0.000657.",
    "metadata": {
      "pid": 11983,
      "state_hash": "27176199460189166217693984681033424446699970654123122262984611706112995793691878597094501817482883383482838715471893685448408621474317089513261416358594534009790191558783794607032376898203418444480440776168050423014559731703224",
      "transition": {
        "protocol_state": {
          "body": {
            "blockchain_state": {
              "timestamp": "1568241600000",
              "staged_ledger_hash": {
                "pending_coinbase_hash": "13260448012835319838158395654777044381396444065393220137989900985394133196488223043689840554640976411077124285028848859749781894303571492517232985196382024903683304592733850455861289438374405785690109436914195715803967796723738",
                "non_snark": {
                  "ledger_hash": "30588831769605338841020419349288689226958711667376868419591095015553230331695633936608323631518249365791289913146685157542586461758544711041113675431614780826932362512320895031163190697806638385557510409221513179489262568564865",
                  "aux_hash": "NbAX11Kdsc1PKibVkNoBjk4gJg9Bwi9jxCbGG6vZBxVrxEWqjf",
                  "pending_coinbase_aux": "5Kqz3bUL4V82sGNtLLpAPr2N2moEjg4M1MnvNRtA7mbu1fGR4UL"
                }
              },
              "snarked_ledger_hash": "29684973129583003581339798741414000740013499350152069286989692722355471078880833269382191543654922606900822736602519851583613364924619078788223228134611581458145813109716990152939079239530350179227799251047020980809922726980197"
            },
            "consensus_state": {
              "next_epoch_data": {
                "epoch_length": "109",
                "ledger": {
                  "hash": "29684973129583003581339798741414000740013499350152069286989692722355471078880833269382191543654922606900822736602519851583613364924619078788223228134611581458145813109716990152939079239530350179227799251047020980809922726980197",
                  "total_currency": 8003000980
                },
                "seed": "15624769950328703120819012729609853039629459035732725434703666326220464242421995049700875803350186219212858014845981802727753365222825610456191472405932989588444625965720394353768305188188054784359052030261402919852079980790526",
                "start_checkpoint": "35741804161884310608002892947638850203254256277633275650850626297214504639878738558062338856424327145102610092326193757367204601999849932458366339249216511502281630507761625608901204085015525393697297037924727278840521878851867",
                "lock_checkpoint": "20871600881077302922623220943509496735064497242484090105799737216650652517261184226412181146866018214461675407117820044905363397603456955620595497980868458246778262986400446348291121381498097425241287387521794441504268344682640"
              },
              "blockchain_length": "173",
              "last_vrf_output": "6v8cy8hee5b8NYnWDpsmbm7Fqmhgy59CHAuGuUaAxRYAsdboXC",
              "total_currency": 8003000980,
              "staking_epoch_data": {
                "epoch_length": "65",
                "ledger": {
                  "hash": "29684973129583003581339798741414000740013499350152069286989692722355471078880833269382191543654922606900822736602519851583613364924619078788223228134611581458145813109716990152939079239530350179227799251047020980809922726980197",
                  "total_currency": 8003000980
                },
                "seed": "2071893303198007985737678972190309212568452221625132024511988170095494148670997278812694070338313361389889122280160253462982652030041813566301365289695187505618174204273471887226695702458395861269694368663558765191107385382142",
                "start_checkpoint": "2071893303198007985737678972190309212568452221625132024511988170095494148670997278812694070338313361389889122280160253462982652030041813566301365289695187505618174204273471887226695702458395861269694368663558765191107385382142",
                "lock_checkpoint": "2071893303198007985737678972190309212568452221625132024511988170095494148670997278812694070338313361389889122280160253462982652030041813566301365289695187505618174204273471887226695702458395861269694368663558765191107385382142"
              },
              "min_epoch_length": "65",
              "has_ancestor_in_same_checkpoint_window": true,
              "checkpoints": {
                "data": {
                  "prefix": [
                    "13912453833836514455460143058478046833882699882437722780091077090655288373133841906509320605076182848112625491391524453854489148838495986431214408192235571355975705393858122293361033535427737039008509846190321205456557990801582"
                  ],
                  "tail": "0"
                },
                "hash": "5965864220448231089575269164059237264853004951235817610628707825686895646193500467065926511059517844671367420859135495877714259084774768783234691329123959733615595060552367267800754487126655882877054900226024381383749586788459"
              },
              "curr_global_slot": "458",
              "epoch_count": "1"
            }
          },
          "previous_state_hash": "1238481947371060291368947092394223092443496437359168656947732425446112147216424406179629208470457603892969708597831856651371784098478884776670991245882822434096559270081975816474032314669190920024002990650311208210344971131088"
        },
        "protocol_state_proof": "<opaque>",
        "staged_ledger_diff": "<opaque>",
        "delta_transition_chain_proof": "<opaque>"
      },
      "peer": "52.41.245.81"
    },
    "input": {
      "type": "log"
    },
    "ecs": {
      "version": "1.0.0"
    },
    "level": "Debug",
    "source": {
      "location": "File \"lib/trust_system/peer_trust.ml\", line 120, characters 56-63",
      "module": "Trust_system__Peer_trust"
    },
    "agent": {
      "type": "filebeat",
      "ephemeral_id": "9f766251-716f-48fa-8393-f0f7d523f1c9",
      "hostname": "golden-hour_us-west-2_seedjoiner_0.us-west-2",
      "id": "9a6b904e-c6d8-429b-b781-d5e3c08b6313",
      "version": "7.0.1"
    }
  },
  "fields": {
    "@timestamp": [
      "2019-09-11T22:43:59.183Z"
    ]
  },
  "highlight": {
    "message": [
      "Increasing trust for peer $peer due to action @kibana-highlighted-field@Trust_system.Actions.Sent_useful_gossip@/kibana-highlighted-field@ (@kibana-highlighted-field@external@/kibana-highlighted-field@ @kibana-highlighted-field@transition@/kibana-highlighted-field@ $@kibana-highlighted-field@state_hash@/kibana-highlighted-field@). New trust is 0.000657."
    ]
  },
  "sort": [
    1568241839183
  ]
}
```

Example Log JSON w/ Object: 
```
{
  "_index": "filebeat-7.0.1-2019.09.09",
  "_type": "doc",
  "_id": "nQ9EFm0BMBTl-AVg40XN",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2019-09-09T13:44:35.545Z",
    "agent": {
      "type": "filebeat",
      "ephemeral_id": "e4b63e93-837b-4874-900d-8988db7f5e51",
      "hostname": "grab-bag_us-west-1_blockproducer_0.us-west-1",
      "id": "f08ab88f-38e7-4162-9c0d-11eacb998ab0",
      "version": "7.0.1"
    },
    "source": {
      "module": "Gossip_net",
      "location": "File \"lib/gossip_net/gossip_net.ml\", line 457, characters 20-27"
    },
    "metadata": {
      "error": "(\"connection attempt timeout\" 163.172.182.148:8302 src/tcp.ml:120:11)",
      "peer": {
        "host": "163.172.182.148",
        "discovery_port": 8303,
        "communication_port": 8302
      },
      "pid": 22429
    },
    "log": {
      "offset": 5417949,
      "file": {
        "path": "/home/admin/test-coda/coda.log"
      }
    },
    "host": {
      "name": "grab-bag_us-west-1_blockproducer_0.us-west-1"
    },
    "ecs": {
      "version": "1.0.0"
    },
    "message": "Retrieving chain ID failed: refusing to connect to [host : 163.172.182.148, discovery_port : 8303, communication_port : 8302]: $error",
    "timestamp": "2019-09-09 13:44:28.804795Z",
    "level": "Warn",
    "input": {
      "type": "log"
    }
  },
  "fields": {
    "@timestamp": [
      "2019-09-09T13:44:35.545Z"
    ]
  },
  "sort": [
    1568036675545
  ]
}
```

### PR DESCRIPTION
**Pull request by jkrauska**
Closes #3418 

In trust layer peers are only known by IP.
In communications peers are known by IP and other metadata (gossip and discovery ports).

This change adjusts how trust layer describes bans to use a new metadata keyword peer_id, which is more usable in this context and doesn't overload the other representation of peer used by other parts of the code.

### CODE REVIEW

File: src/lib/trust_system/peer_trust.ml [hunk 1]
```diff
@@ -126,7 +126,7 @@ struct
           Logger.faulty_peer_without_punishment logger ~module_:__MODULE__
             ~location:__LOC__
             ~metadata:
-              ( [ ("peer", Peer_id.to_yojson peer)
```
Comment (nholland94) [inline src/lib/trust_system/peer_trust.ml]: You need to also update the interpolation of `$peer` in the message string below.
