### PR TITLE
 fix gossip tcp error (fixes  #2157)

### LINKED ISSUE #2157: Gossip TCP Error
Non crashing, but I'm seeing this on a daemon in a testnet:

```
{
  "timestamp": "2019-04-05 00:58:48.055149Z",
  "level": "Error",
  "source": {
    "module": "Gossip_net",
    "location": "File \"lib/gossip_net/gossip_net.ml\", line 266, characters 70-77"
  },
  "message": "(monitor.ml.Error Not_found(\\\"Raised at file \\\\\"src/hashtbl.ml\\\\\", line 275, characters 23-43\\\"\\\"Called from file \\\\\"src/hashtbl.ml\\\\\" (inlined), line 277, characters 4-47\\\"\\\"Called from file \\\\\"lib/gossip_net/gossip_net.ml\\\\\", line 310, characters 18-102\\\"\\\"Called from file \\\\\"src/deferred1.ml\\\\\", line 20, characters 40-45\\\"\\\"Called from file \\\\\"src/job_queue.ml\\\\\" (inlined), line 120, characters 2-5\\\"\\\"Called from file \\\\\"src/job_queue.ml\\\\\", line 159, characters 6-47\\\"\\\"Caught by monitor Tcp.collect_errors\\\"))",
  "metadata": {
    "pid": 9158
  }
}
```

Maybe implys bad/corrupt data over the wire?

### PR DESCRIPTION
**Pull request by deepthiskumar**
Fixed the issue caused by a race condition.
Also, re-throwing any exception in the handler

Checklist:

- [ ] Tests were added for the new behavior
- [X] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [ ] Does this close issues? List them:

Closes #2157

### CODE REVIEW

File: src/lib/gossip_net/gossip_net.ml [hunk 1]
```diff
@@ -218,7 +222,10 @@ module Make (Message : Message_intf) :
                      !"Peer %{sexp: Unix.Inet_addr.t} banned, disconnecting."
                      addr ;
                    Deferred.List.iter (Hashtbl.to_alist conn_list)
-                     ~f:(fun (_, conn) -> Rpc.Connection.close conn ) )) ;
+                     ~f:(fun (_, conn_opt) ->
+                       match conn_opt with
+                       | None -> return ()
```
Comment (enolan) [inline src/lib/gossip_net/gossip_net.ml]: There's another race here, if we ban a peer and there is a connection from that peer that hasn't called `connection_state` yet. This code should wait until there is a connection object to close. Best way to do that is probably to change the `Rpc.Connection.t option` to `Rpc.Connection.t Ivar.t`, put an empty Ivar in where you had `None` before, fill it where you set the option to `Some` and use `Ivar.read` here.

**Comment by enolan** [comment]
lgtm
