### PR TITLE
Removed exn from visualization code

### LINKED ISSUE #1806: Visualizing the transition frontier stops working after a while
When I run networks, visualizing the frontier works for a while, but after some point, every time I try I'll get an error message:

```
_build/install/default/bin/coda client visualize-frontier frontier.dot && xclip -selection c <frontier.dot
Could not save file: ((rpc_error
  (Uncaught_exn
   ((location "server-side rpc computation")
    (exn
     (monitor.ml.Error "Option.value_exn None"
      ("Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30"
       "Called from file \"src/option.ml\", line 69, characters 4-21"
       "Called from file \"src/lib/transition_frontier/transition_frontier.ml\", line 500, characters 16-106"
       "Called from file \"list.ml\", line 117, characters 24-34"
       "Called from file \"src/avltree.ml\", line 381, characters 20-50"
       "Called from file \"src/hashtbl.ml\", line 223, characters 27-60"
       "Re-raised at file \"src/hashtbl.ml\", line 231, characters 6-15"
       "Called from file \"src/lib/transition_frontier/transition_frontier.ml\", line 506, characters 20-41"
       "Called from file \"src/exn.ml\", line 72, characters 8-11"
       "Re-raised at file \"src/exn.ml\", line 75, characters 6-15"
       "Called from file \"src/option.ml\", line 183, characters 23-28"
       "Called from file \"src/fn.ml\" (inlined), line 23, characters 22-27"
       "Called from file \"src/lib/coda_lib/coda_lib.ml\", line 437, characters 4-95"
       "Called from file \"src/app/cli/src/coda_main.ml\", line 1387, characters 16-49"
       "Called from file \"src/result.ml\", line 161, characters 9-15"))))))
 (connection_description <created-directly>) (rpc_tag Visualize_frontier)
 (rpc_version 0))
```

It's referencing this code:
```ocaml
    let to_graph t =
      fold t ~init:empty ~f:(fun (node : Node.t) graph ->
          let graph_with_node = add_vertex graph node in
          List.fold node.successor_hashes ~init:graph_with_node
            ~f:(fun acc_graph successor_state_hash ->
              add_edge acc_graph node
                ( State_hash.Table.find t.table successor_state_hash
                |> Option.value_exn ) ) )
```

### LINKED ISSUE #1842: Proposer Crash in Testnet
Crash on proposer in AWS testnet.

Git SHA:
abeb10c2fcbe0b997316b9ea5e1d10d23d63d595

trace:

```
(monitor.ml.Error "Option.value_exn None"
 ("Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30"
  "Called from file \"src/option.ml\", line 69, characters 4-21"
  "Called from file \"lib/transition_frontier/transition_frontier.ml\", line 458, characters 16-106"
  "Called from file \"list.ml\", line 117, characters 24-34"
  "Called from file \"src/avltree.ml\", line 381, characters 20-50"
  "Called from file \"src/hashtbl.ml\", line 223, characters 27-60"
  "Re-raised at file \"src/hashtbl.ml\", line 231, characters 6-15"
  "Called from file \"lib/transition_frontier/transition_frontier.ml\", line 464, characters 20-41"
  "Called from file \"src/exn.ml\", line 72, characters 8-11"
  "Re-raised at file \"src/exn.ml\", line 75, characters 6-15"
  "Called from file \"src/option.ml\", line 183, characters 23-28"
  "Called from file \"src/fn.ml\" (inlined), line 23, characters 22-27"
  "Called from file \"lib/coda_lib/coda_lib.ml\", line 439, characters 4-95"
  "Called from file \"app/cli/src/coda_main.ml\", line 1322, characters 4-48"
  "Called from file \"app/cli/src/coda_main.ml\", line 1523, characters 8-42"
  "Called from file \"src/monitor.ml\", line 65, characters 10-15"
  "Re-raised at file \"src/monitor.ml\", line 72, characters 8-23"
  "Called from file \"src/job_queue.ml\" (inlined), line 120, characters 2-5"
  "Called from file \"src/job_queue.ml\", line 159, characters 6-47"))
```

Logs attached from this node.
[2019-03-12-proposer-crash.tar.gz](https://github.com/CodaProtocol/coda/files/2958773/2019-03-12-proposer-crash.tar.gz)

### PR DESCRIPTION
**Pull request by johnwu93**
- Made it clearer to client when you are bootstrapping and when you are not

Visualizations should not fail randomly anymore because it should be impossible to throw an exception involving this code

Checklist:

- [ ] Tests were added for the new behavior
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [X] Does this close issues? List them:

Closes #1842
Closes #1806

### CODE REVIEW

File: src/app/cli/src/client.ml [hunk 1]
```diff
@@ -482,8 +482,11 @@ let visualize_frontier =
        Command.Param.(anon @@ ("output-filepath" %: string))
        ~f:(fun port filename ->
          match%map dispatch Visualize_frontier.rpc filename port with
-         | Ok () ->
+         | Ok (`Active ()) ->
              printf !"Successfully wrote the visual at location %s." filename
+         | Ok `Bootstrapping ->
+             printf
+               !"Could not visualize frontier becuase we are bootstrapping."
```
Comment (cmr) [inline src/app/cli/src/client.ml]: because

File: src/app/cli/src/coda_main.ml [hunk 2]
```diff
@@ -1291,8 +1291,13 @@ module Run (Config_in : Config_intf) (Program : Main_intf) = struct
   let clear_hist_status ~flag t = Perf_histograms.wipe () ; get_status ~flag t
 
   let log_shutdown ~frontier_file ~log t =
-    visualize_frontier ~filename:frontier_file t |> ignore ;
-    Logger.info log "Logging the transition_frontier at %s" frontier_file
+    match visualize_frontier ~filename:frontier_file t with
+    | `Active () ->
+        Logger.info log "Logging the transition_frontier at %s" frontier_file
```
Comment (cmr) [inline src/app/cli/src/coda_main.ml]: can you make these strings agree with the ones from `client.ml`?
