### PR TITLE
Fix/defunctorize transition frontier

### LINKED ISSUE #1229: Transition Frontier depends directly on Coda-base ; no functor

### PR DESCRIPTION
**Pull request by bkase**
We removed most of the functor arguments on transition_frontier.ml

It builds.

Closes #1229

### CODE REVIEW

**Comment by bkase** [comment]
History is weird, but it seems reviewable

File: src/lib/transition_frontier/transition_frontier.ml [hunk 1]
```diff
@@ -1,147 +1,144 @@
...
+      -> Transaction_snark_scan_state.Diff.t
+      -> logger:Logger.t
+      -> t Or_error.t
+  end = struct
+    (* TODO *)
+
+    type t = Ledger_builder.t
+
+    let create ~transaction_snark_scan_state ~ledger =
+      Async.Thread_safe.block_on_async_exn (fun () ->
```
Comment (cmr) [inline src/lib/transition_frontier/transition_frontier.ml]: I don't like this. @bkase explained in person that, pretty soon, @deepthiskumar will have made these things non-async, so this is the temporary glue.

File: src/lib/transition_frontier/transition_frontier.ml [hunk 2]
```diff
@@ -1,147 +1,144 @@
...
+    let ledger t = Ledger_builder.ledger t
+
+    let apply t diff ~logger =
+      let derive_mask ledger =
+        let mask = Ledger.Mask.create () in
+        Ledger.register_mask ledger mask
+      in
+      let ledger = Ledger_builder.ledger t in
+      let masked_ledger = derive_mask ledger in
+      Async.Thread_safe.block_on_async_exn (fun () ->
```
Comment (cmr) [inline src/lib/transition_frontier/transition_frontier.ml]: (same as above)
