### PR TITLE
Log creation, termination of children

### LINKED ISSUE #3430: Child processes defunct, don't get restarted and/or parent doesn't die
Condition:

```
ps auxf 
...
admin    11987  5.7 77.9 14533924 12359036 ?   Sl   Sep10 234:55 coda daemon -background -tracing -no-bans -log-json -log-level Trace -client-port 8301 -external-port 8302 -config-directory /home/admin/test-coda -external-ip 54.69.139.81 -rest-port 8304 -peer 34.212.21.74:8303 -peer 54.241.142.143:8303
admin    12157  0.0  0.0      0     0 ?        Z    Sep10   1:56  \_ [exe] <defunct>
admin    12171  0.9  0.0      0     0 ?        Z    Sep10  37:34  \_ [exe] <defunct>
admin     4302  1.1  0.0 1073766168 6220 ?     S    17:29   0:01  \_ coda-kademlia test 0.0.0.0
```

Note that two sub processes (verifier?  don't know the other one) are defunct/dead.

But parent doesn't seem to notice.

host:
golden-hour_us-west-2_seedjoiner_0

logs here:
test-coda-CRASH-2019-09-13_17-34-14

Couldn't find any knowledge in log showing that we knew the subprocesses were dead.

### PR DESCRIPTION
**Pull request by psteckler**
Log creation of child processes, including their pid. Did I miss any?

Check once a minute for terminated children, log if found.

A step towards addressing #3430.

### CODE REVIEW

**Comment by jkrauska** [comment]
@psteckler we need to do more.

they terminate now and we keep on going, unable to process blocks.

- why did they die? (where are their logs?)
- can we restart them? (is this safe?)
- if we cannot safely restart, we should probably die so that we can be restarted, as we cannot continue to process information without them.

see also: aren't calls to have them do work going unanswered?  why aren't we detecting THIS too?

**Comment by psteckler** [comment]
@jkrauska can we do additional features in another PR, and start with this?

**Comment by psteckler** [comment]
For a later PR: either terminate the parent, or restart children.

**Comment by jkrauska** [comment]
> @jkrauska can we do additional features in another PR, and start with this?

ok -- move in the right direction -- small PRs!

**Comment by psteckler** [comment]
Added termination of daemon on verifier or prover termination. We could change those to restarts, if desired.

**Comment by psteckler** [comment]
Added logging when child failure handlers are called.

File: src/app/cli/src/coda.ml [hunk 1]
```diff
@@ -632,9 +632,59 @@ let daemon logger =
            Auxiliary_database.External_transition_database.create ~logger
              external_transition_database_dir
          in
+         (* log terminated child processes *)
+         let pids = Child_processes.Termination.create_pid_set () in
+         let rec terminated_child_loop () =
+           match
+             try Unix.wait_nohang `Any
```
Comment (cmr) [inline src/app/cli/src/coda.ml]: How does this interact with the other calls to `Process.wait` in our codebase?

**Comment by cmr** [comment]
Looks like we should start unifying some of these args into a context record...

**Comment by psteckler** [comment]
@cmr like the logger/pids/trust system?

File: src/app/cli/src/coda.ml (hunk 1 above)
Comment (psteckler) [reply src/app/cli/src/coda.ml]: I think it will be OK:

  - If there's a pending `wait` elsewhere, this call should return with `None`, and have no effect on the other `wait`
  - if this call returns `Some`, meaning the process has terminated, the other `wait` should
    return with the same code it would have without this call

At least, that's what I understand from reading `man wait`

File: src/app/cli/src/coda.ml [hunk 2]
```diff
@@ -632,9 +632,59 @@ let daemon logger =
...
+             with
+             | Unix.Unix_error (errno, _, _)
+             when Int.equal (Unix.Error.compare errno Unix.ECHILD) 0
```
Comment (enolan) [inline src/app/cli/src/coda.ml]: You can use regular `=` here

File: src/lib/child_processes/termination.ml [hunk 3]
```diff
@@ -0,0 +1,20 @@
...
+let create_pid_set () = Pid.Hash_set.create ()
+
+let register_process t process = Hash_set.add t (Process.pid process)
+
+let check_terminated_child t child_pid logger =
+  if Hash_set.mem t child_pid then (
+    Logger.error logger ~module_:__MODULE__ ~location:__LOC__
+      "Child process with pid $child_pid has terminated; terminating parent \
+       process $pid"
+      ~metadata:[("child_pid", `Int (Pid.to_int child_pid))] ;
```
Comment (enolan) [inline src/lib/child_processes/termination.ml]: You're missing the parent pid in the metadata.

File: src/lib/transition_frontier_persistence/rpc_worker.ml [hunk 4]
```diff
@@ -89,12 +89,22 @@ module Make (Inputs : Intf.Worker_inputs) = struct
 
   type t = {connection: Rpc_worker.Connection.t; process: Process.t}
 
-  let create ~directory_name =
+  let create ~directory_name ~logger =
```
Comment (enolan) [inline src/lib/transition_frontier_persistence/rpc_worker.ml]: This doesn't get tracking?

File: src/app/cli/src/coda.ml (hunk 2 above)
Comment (psteckler) [reply src/app/cli/src/coda.ml]: yes, but I try to avoid polymorphic `=`

File: src/lib/child_processes/termination.ml (hunk 3 above)
Comment (psteckler) [reply src/lib/child_processes/termination.ml]: I believe it's contained there by default.

File: src/lib/transition_frontier_persistence/rpc_worker.ml (hunk 4 above)
Comment (psteckler) [reply src/lib/transition_frontier_persistence/rpc_worker.ml]: I didn't want to add it to the termination set, since I don't believe it's as crucial as the verifier or prover.

File: src/lib/child_processes/termination.ml (hunk 3 above)
Comment (psteckler) [reply src/lib/child_processes/termination.ml]: In the past, when I've added `pid` to metadata, I get an error from `Map` saying there's a duplicate entry.

File: src/lib/transition_frontier_persistence/rpc_worker.ml (hunk 4 above)
Comment (psteckler) [reply src/lib/transition_frontier_persistence/rpc_worker.ml]: if the persistence process terminates, it'll get logged, but the daemon will continue

File: src/lib/child_processes/termination.ml (hunk 3 above)
Comment (enolan) [reply src/lib/child_processes/termination.ml]: ok, that makes sense
