### PR TITLE
fix for one of the testnet prover failures

### LINKED ISSUE #4294: [CRASH] Prover failed: $error, Prover failed to prove freshly generated transition: $error
Since roughly 10am PST I have been observing Block producers produce blocks but the block length did not increase.

Screen Shot 2020-01-27 at 7 17 00 PM
Slots have been won, but produced blocks are not committed to the blockchain

Checking the logs, I observed a pattern where blocks are produced but result in prover errors. The stacktraces are long and include the whole ledger (10k accounts) so the stack trace is trimmed. 

**Prover failed to prove freshly generated transition: $error:**
```
{"timestamp":"2020-01-27 23:46:03.791853Z","level":"Error","source":{"module":"Proposer","location":"File \"src/lib/proposer/proposer.ml\", line 343, characters 72-79"},"message":"Prover failed to prove freshly generated transition: $error","metadata":{"error":"( \"Snarky.Checked_runner.Runtime_error(_, _, _, _)\\\n \\n\\\n \\nEncountered an error while evaluating the checked computation:\\\n \\n (Failure\\\n \\n \\\"Constraint unsatisfied (unreduced):\\\\\\\n \\n \\\\nfield_inverse\\\\\\\n \\n \\\\nChecked.inv\\\\\\\n \\n \\\\nassert_non_zero: File \\\\\\\"src/lib/snarky/src/snark0.ml\\\\\\\", line 355, characters 4-114\\\\\\\n \\n \\\\nany: File \\\\\\\"src/lib/snarky/src/snark0.ml\\\\\\\", line 562, characters 8-101\\\\\\\n \\n \\\\nFile \\\\\\\"src/lib/coda_base/transition_system.ml\\\\\\\", line 240, characters 17-24\\\\\\\n \\n \\\\nmain: File \\\\\\\"src/lib/coda_base/transition_system.ml\\\\\\\", line 152, characters 4-4066\\\\\\\n \\n \\\\n\\\\\\\n \\n \\\\nConstraint:\\\\\\\n \\n \\\\n(((basic(R1CS(Add(Add(Constant 0)(Scale 1(Var 257013)))(Scale 1(Var 257012)))(Var 257015)(Constant 1)))(annotation(field_inverse))))\\\\\\\n \\n \\\\nData:\\\\\\\n \\n \\\\nR1CS 0 0 1\\\")\\\n \\n\\\n \\nLabel stack trace:\\\n \\nChecked.inv\\\n \\nassert_non_zero: File \\\"src/lib/snarky/src/snark0.ml\\\", line 355, characters 4-114\\\n \\nany: File \\\"src/lib/snarky/src/snark0.ml\\\", line 562, characters 8-101\\\n \\nFile \\\"src/lib/coda_base/transition_system.ml\\\", line 240, characters 17-24\\\n \\nmain: File \\\"src/lib/coda_base/transition_system.ml\\\", line 152, characters 4-4066\\\n \\n\\\n \\n\\\n \\nRaised at file \\\"stdlib.ml\\\", line 33, characters 17-33\\\n \\nCalled from file \\\"src/lib/snarky/src/checked_runner.ml\\\", line 173, characters 8-350\\\n \\nCalled from file \\\"src/lib/snarky/src/checked_runner.ml\\\", line 322, characters 8-12\\\n \\n\")","internal_transition":{"snark_transition":{"blockchain_state":{"staged_ledger_hash":{"non_snark":{"ledger_hash":"12436923826301403049189783640917577410121118326215453453208750443990671799763835310429725123006757437171526627515740594213075787991793148592435780344474393860724287031490913893709980368906805033102444801962417149908412962761006","aux_hash":"NpfGhrh9rLpLeVxuGZk1G7kAueeGSKVmvVrVZbfGQtVEGenZiB","pending_coinbase_aux":"5LGABHcPvhDrYFdTDfmkCEvgE3LA2mgUDa8kJgJ3msofurGCHnW"},"pending_coinbase_hash":"9067075111283599579150930017623248346023026790975971933529233458336839282780849648398194501998585998161332349251174609563580245523550021835296879320277802470624297433063745153553343077618317305249513606602235726377943693711670"},"snarked_ledger_hash":"4556160911940315274457564845307891375833879456032896398418976458191122289348646235517657473089572854682378412104669695035650875983554068087068359091202785472667603737257677706894425047477464567600818530544212298781995506406331","timestamp":"1580168700000"},"consensus_transition":"1785","sok_digest":"�Ի�ZК�ݹ���Ǎ��\u0007VN�\u001f)a+\u0012��\u0017}F�","supply_increase":"320","ledger_proof":"5E5J8je6PwLQ2kviovYKBZFiwDSgBV8AW5xUv85ftZ8gy7XMzMnpouVJ8FYm47dQkTETos2G2Wtq7ovuH5iMAJP2eQDJcsSpiXPZZpCCh2RaixksJFFPXxeJ3QoFGtgMGw93m2L7FTkVqUfsKVPKKVfo6tTR2H5rrTACxnXXVXUfJD1Y8LiqUdudnjsZR43pK9dNSpDKJk2Kx9v7FvGues8zYB49WLYQXRM1XTCtz7vbK4MM7xVDEigDjfxNhqbPbgGX39FvoSPjAAi9te5E8HzAJPozksWzLLLsGNXbFjdC9GYY6F7jHU6YWLitafWihWBSn451mfMC35tAzoTiGYJDYqExQ69bn9WyM5VAFeTvWX7G3EXX3CJ27GUPBorDfaGoJC3xRZsMtoHNGBdjR83JXW4f3kKahEzfYVMBPGyR2dXeJpFvRbUB8NhHxW7DW6xaE79FhH3vZkYcnJGiTkUYTocxnfg8ZVEo5L3yEbpR2Cj5azjsg5YVL4DVFJmrbfYuYVL5eU4FukbKbpQRToXyoAL3Dmb6Z3HNexzdM4xkt4yAVwFtu8vxKQWF4r1V5jKxHrfmcKJyXxgUTfVwc1STnkB1CWbNCKMc2D2As34etCRq7pDeowtF5fHZacFR7hBTkZAYStjV3d6sdyQ5vRKz7aHMFrFkxruStqa6xeoHJjRUs3k7z28vAd4oVoeJjJtLnQFEpTLtspLp6ikpxDxqDdvdNxoLCfgGXZP1mpCjB8XWfhbtRpSGtojXzxpQrr1aKrXbfcS4w9uNevpn7wYqYnHkF21eUG3cSkRg8BzXxHqBHX2UeaRbAm4UhUhr4tpK5qepUQKp9qHbBtVYsGrRt2FYeweWg1oMaFdjinq5gtdrUwphCXVbfg4QgM98yiKukbr7nvqHNvF3728hPRYVDQbpYvB5N2T1wkANyEHYtdu7tdPMtbc88PbKrevtu8hq6xVHdFXg6uNsqhoKHMPX6SxMQGdNi6ZXMrAebCMHpTbieVcVf2XeiTk3QPLLdLcaQDkQVrySL4f9iVaSLaDu8shUg7oknt5KF9XFr2YBNNAWQFr6pFHeuZZ4c1QXPJhs64GsZ3QmvUxb9QkGqJWEQCEBgsUi8f8cCPLbTmRGwLY7DBuYhYutmuZHNaLsZ3ZwTmQgVAWcgMf6PwUxLGp4uPqgFcnTkb1qojqCGfSTVjDw1J5sZ1g7u4EjXBKD6qTqQx1p177ydhDKHq88g1oEcHCdpT7toJrK4uwZtnLPowTLKNBqgvgFc1vXwx4qSdkhd19cS5KdruMmFH4dkpwN2B4o6HpreUdtdDNJVc85LQsZ6Px3mXC6CpuPGFEm7u6igSEDKddMashb3iv7UkWoCMtHANp8yuutSuuHUTcYspt7xYkFSJJX2zBtNhckicyGrZndFq5ronof6FPnojPTh8YgkFbfqp1d5tkuwZopevJjELWF7v5Nii9dvELA3jyHuqmTp3YaHfEyUk1ydav7BjAsXRzAeG24GRdNyd5K9PKyd83dJ7ZiL7SM5uorpCHkt9tY8MQkHaWDWBkioPVBhyaHSHga7buSFNXGZfDn3yonxVS9E6ov2CZVMsCn4Gktfgut4VkFiVknALXFPL3PKT6zwJ3J69Da1JmBwxML5gw37LjKa5g7hP5hHMfBgue8aLWUQrEgezG2VfukBa4Gv8HGdFFPUeMgGWvAkKYudp7svmBMHuKRtjhKtw6oZDGsmVspLFHJoUPQJ8bBgLLdubeFedCqGyy4E3WhnBo1HiM8d6fMeG1AJr6KAmt7wvjFB4CZSTWc8g27GMLmVhqGRcYaqr9JDqZGKFyhDuMkSBq7m3p36DekQHcin3yqcVue3Dn4erjtMqjpRhH8NWpswvrSRaYQHEQrAe6DCd7YWPNxfAwSq6wprUVXjJkXK9BhbQwRDLoKXLTTmUykxEvCmmBNiQ3V5b1c95GqmqucPT3wZAjvtSAm8uLjDD4yCS4GQigU5sKsuEZK86ov29kk1nx8AjMP4vTEQkpnjnesetPm6zHrGEHhdcWccyyanbN8N4oQUkXsAjiYc7PdDSZdzQq7BGPKEKsGFj8Crxn7BFgmgi9coKVoZN6k9Gev1Fe4fP3Dt7eNphvKe7wCJJmJTbZNnjsNGZ38rdJnxoufWron7PtDzmXUMvSH1vx8YmDeyaUeuhJjwjkQdZHSE2SFDz6E4SccyuGrwqiUY5AEndPYxFcKaoem8iP4ebhQ44vREVHBrD5PxpH6NcpfxfUT6hucQy5DJMiyyXLBDwypiHuPnVdfu9NrJirHPD6pNPQAA3q3aCYbcvjhQqxvhF365sC6xcmJJDEdY1Lq8SxoTRi2YSKCfwtufU3MW7MwMcJMijU5JVaQTqfKBKSm1mQjWeMdMdDwL1s1","coinbase_receiver":"4vsRCVQAkUfP9wGLx8yiKv3GPVATRBFW4kuzj2XA8tihDjgfmNFNHZNjWsynvHNJbTQcr8atGquTieHAQtD3j9odMiS9ApZqKcFTzHggYwP4haXm6LgsBXei5vgDCFa88ZRo9Kzi9sHFRTkK","coinbase_amount":"20","pending_coinbase_action":["Update_two_coinbase_in_second"]},"prover_state":{"delegator":421,"ledger":{"indexes":
```
**nEncountered an error while evaluating the checked computation:**
```
Prover failed: $error","metadata":{"error":"( \"Snarky.Checked_runner.Runtime_error(_, _, _, _)\\\n \\n\\\n \\nEncountered an error while evaluating the checked computation:\\\n \\n (Failure\\\n \\n \\\"Constraint unsatisfied (unreduced):\\\\\\\n \\n \\\\nfield_inverse\\\\\\\n \\n \\\\nChecked.inv\\\\\\\n \\n \\\\nassert_non_zero: File \\\\\\\"src/lib/snarky/src/snark0.ml\\\\\\\", line 355, characters 4-114\\\\\\\n \\n \\\\nany: File \\\\\\\"src/lib/snarky/src/snark0.ml\\\\\\\", line 562, characters 8-101\\\\\\\n \\n \\\\nFile \\\\\\\"src/lib/coda_base/transition_system.ml\\\\\\\", line 240, characters 17-24\\\\\\\n \\n \\\\nmain: File \\\\\\\"src/lib/coda_base/transition_system.ml\\\\\\\", line 152, characters 4-4066\\\\\\\n \\n \\\\n\\\\\\\n \\n \\\\nConstraint:\\\\\\\n \\n \\\\n(((basic(R1CS(Add(Add(Constant 0)(Scale 1(Var 257013)))(Scale 1(Var 257012)))(Var 257015)(Constant 1)))(annotation(field_inverse))))\\\\\\\n \\n \\\\nData:\\\\\\\n \\n \\\\nR1CS 0 0 1\\\")\\\n \\n\\\n \\nLabel stack trace:\\\n \\nChecked.inv\\\n \\nassert_non_zero: File \\\"src/lib/snarky/src/snark0.ml\\\", line 355, characters 4-114\\\n \\nany: File \\\"src/lib/snarky/src/snark0.ml\\\", line 562, characters 8-101\\\n \\nFile \\\"src/lib/coda_base/transition_system.ml\\\", line 240, characters 17-24\\\n \\nmain: File \\\"src/lib/coda_base/transition_system.ml\\\", line 152, characters 4-4066\\\n \\n\\\n \\n\\\n \\nRaised at file \\\"stdlib.ml\\\", line 33, characters 17-33\\\n \\nCalled from file \\\"src/lib/snarky/src/checked_runner.ml\\\", line 173, characters 8-350\\\n \\nCalled from file \\\"src/lib/snarky/src/checked_runner.ml\\\", line 322, characters 8-12\\\n \\n\")","input-bin-io":
```

### PR DESCRIPTION
**Pull request by deepthiskumar**
When verifying ledger proof, the source pending coinbase stack corresponding to the ledger proof is now derived from the deleted stack (empty or not, it is tracked in the `init` field of the deleted stack)

Also, added full-test that generates` 2*slots_per_epoch` blocks to the tests that run daily

Checklist:

- [X] Tests were added for the new behavior
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [X] Does this close issues? List them:

closes #4294

### CODE REVIEW

File: src/app/cli/src/tests/full_test.ml [hunk 1]
```diff
@@ -50,6 +50,9 @@ let medium_curves = false
 [%%if
 time_offsets = true]
 
+[%%inject
```
Comment (mrmr1993) [inline src/app/cli/src/tests/full_test.ml]: I think this needs to be hoisted out of the `[%%if ]` above, otherwise it's undefined when `time_offsets = false`

Comment (deepthiskumar) [reply src/app/cli/src/tests/full_test.ml]: Yes, just fixed it. Thank you :)
