### PR TITLE
Synchronously stop snark workers

### LINKED ISSUE #3231: Snark worker is not turned off properly in integration tests
Sometimes integration tests fails because snark worker isn't shut down properly.
The following is an example:
https://201325-114581326-gh.circle-artifacts.com/0/home/opam/project/test_logs/1565995854/test_postake_txns/coda-shared-state-test.log
In this one, the test went on well. But at the end when we shut down the two nodes, the shut down failed.

The correct order of shutdown should be:
0. turn the status of the node to be offline
1. shut down the snark worker
2. shut down the connection
3. shut down the subprocess

### PR DESCRIPTION
**Pull request by ghost-not-in-the-shell**
This PR undos #3219.

The reason we introduced #3219 is that turning off snark worker takes a while, and this would cause some bug in long-fork integration test. So in #3219 we try to asynchronously stop snark worker. But this would cause some other bug as described in #3231. This proper fix is to change the integration test infrastructure, so that once the nodes are offline, prefix-check should also be turned off.

Close #3231

### CODE REVIEW

File: src/app/cli/src/tests/coda_worker_testnet.ml [hunk 1]
```diff
@@ -278,14 +278,15 @@ let start_prefix_check logger workers events testnet ~acceptable_delay =
...
        if
-         not
-           ( diff
-           < Time.Span.to_sec acceptable_delay
-             +. epsilon
-             +. Int.to_float
-                  ( (Consensus.Constants.c - 1)
-                  * Consensus.Constants.block_window_duration_ms )
-                /. 1000. )
+         Array.existsi testnet.status ~f:(fun i _ -> Api.synced testnet i)
```
Comment (wu-s-john) [inline src/app/cli/src/tests/coda_worker_testnet.ml]: Shouldn't this be?

```
Array.forall testnet.status ....
```

Comment (wu-s-john) [reply src/app/cli/src/tests/coda_worker_testnet.ml]: Actually. nevermind. I read this wrong.
