### PR TITLE
Fix overly-eager bootstrap log message

### LINKED ISSUE #2968: Investigate why we frequently jump between boostrap/sync
Screen Shot 2019-07-23 at 9 08 49 PM

### PR DESCRIPTION
**Pull request by cmr**
This log seems like it needs to be debounced as well.

Closes #2968

### CODE REVIEW

File: src/lib/coda_lib/coda_lib.ml [hunk 1]
```diff
@@ -164,24 +164,25 @@ let sync_status t =
...
-              Logger.info (Logger.create ()) ~module_:__MODULE__
-                ~location:__LOC__ "Coda daemon is now connecting" ;
+              Logger.info t.config.logger ~module_:__MODULE__ ~location:__LOC__
+                "Coda daemon is now connecting" ;
               `Connecting )
             else if `Empty = first_message then (
-              Logger.info (Logger.create ()) ~module_:__MODULE__
-                ~location:__LOC__ "Coda daemon is now listening" ;
+              Logger.info t.config.logger ~module_:__MODULE__ ~location:__LOC__
+                "Coda daemon is now listening" ;
```
Comment (bkase) [inline src/lib/coda_lib/coda_lib.ml]: these need to be debounced too

Comment (bkase) [reply src/lib/coda_lib/coda_lib.ml]: (evidence: if you spam coda status before bootstrap starts, these spam in the same way)

Comment (cmr) [reply src/lib/coda_lib/coda_lib.ml]: This PR doesn't debounce at all. I can do that in this PR I think but I'd rather leave it to @wu-s-john. If these lines are logged, it should be because that's the true status of the daemon- even if it's already told you that twice already.

**Comment by cmr** [comment]
:+1: thank you @wu-s-john

File: src/lib/coda_lib/coda_lib.ml [hunk 2]
```diff
@@ -151,43 +137,43 @@ let sync_status _ =
...
             Option.value_map active_status
-              ~default:
-                ( Logger.info (Logger.create ()) ~module_:__MODULE__
-                    ~location:__LOC__ "Coda daemon is now bootstrapping" ;
-                  `Bootstrap )
-              ~f:(fun _ ->
-                Logger.info (Logger.create ()) ~module_:__MODULE__
-                  ~location:__LOC__ "Coda daemon is now synced" ;
-                `Synced ) )
+              ~default:(fun () ->
```
Comment (mrmr1993) [inline src/lib/coda_lib/coda_lib.ml]: It might be clearer to turn this into a `match` statement instead?
