### PR TITLE
error message for duplicate account

### LINKED ISSUE #5029: [Logging] Add log for duplicate key in genesis ledger
When a duplicate key is present in the JSON genesis ledger, the ledger generation should output a helpful error as opposed to a failed assertion crash.

### PR DESCRIPTION
**Pull request by deepthiskumar**
Closes #5029

### CODE REVIEW

File: src/lib/coda_base/ledger.ml [hunk 1]
```diff
@@ -240,7 +240,12 @@ module Ledger_inner = struct
 
   let create_new_account_exn t pk account =
     let action, _ = get_or_create_account_exn t pk account in
-    assert (action = `Added)
+    if action = `Existed then
+      failwith
+        (sprintf
+           !"Could create a new account with pk \
```
Comment (psteckler) [inline src/lib/coda_base/ledger.ml:246]: think `not` is missing
