### PR TITLE
If ledger transfer fails, delete DB and try again

### LINKED ISSUE #2991: "Merkle roots differ after transfer" after node is running for a while
> This morning my node was looping with timeouts in the log.    I stopped and restarted, and it has now crashed with "Merkle roots differ after transfer: got unexpected result"

### PR DESCRIPTION
**Pull request by cmr**
A brute-force workaround to close #2991

### CODE REVIEW

File: src/lib/coda_lib/coda_lib.ml [hunk 1]
```diff
@@ -343,11 +343,26 @@ let create_genesis_frontier (config : Config.t) ~verifier =
...
-  let root_snarked_ledger =
-    Ledger_transfer.transfer_accounts ~src:genesis_ledger ~dest:ledger_db
+  let%bind root_snarked_ledger =
+    match load () with
+    | _, Ok l ->
+        return l
+    | ledger_db, Error _ ->
+        (* Persisted state was bogus. Give up on the ledger contents, we'll bootstrap. *)
+        Ledger.Db.close ledger_db ;
+        let%map () =
```
Comment (psteckler) [inline src/lib/coda_lib/coda_lib.ml]: should this action be logged? ... it's doing something kind of intrusive ...

Comment (cmr) [reply src/lib/coda_lib/coda_lib.ml]: Yes, it should be.

Comment (psteckler) [reply src/lib/coda_lib/coda_lib.ml]: I mean, the `remove_dir`, is that / should it be logged?
