### PR TITLE
Fix/unregistered mask testnet

### LINKED ISSUE #2969: Daemon crashes due to a merkle mask issue
```
  ☠  Coda Daemon crashed. The Coda Protocol developers would like to know why!

  Please:
    Open an issue:
      https://github.com/CodaProtocol/coda/issues/new

    Briefly describe what you were doing, and include the last 20 lines from .coda-config/coda.log.
    And then paste the following:

    (monitor.ml.Error
  (Failure
    "Couldn't unregister mask with UUID 0e8d45b1-fe70-305e-4375-ab4b1e74dd74 from parent e6f51a1d-9c2f-3815-a744-30ab374f49ba, mask not registered with that parent")
  ("Raised at file \"stdlib.ml\", line 33, characters 17-33"
    "Called from file \"src/lib/merkle_mask/maskable_merkle_tree.ml\", line 159, characters 12-72"
    "Called from file \"src/lib/coda_base/ledger.ml\" (inlined), line 167, characters 35-79"
    "Called from file \"src/lib/transition_frontier/transition_frontier.ml\", line 784, characters 24-63"
    "Called from file \"src/lib/transition_frontier/transition_frontier.ml\", line 787, characters 14-35"
    "Called from file \"list.ml\", line 106, characters 12-15"
    "Called from file \"src/list0.ml\" (inlined), line 26, characters 40-75"
    "Called from file \"src/lib/transition_frontier/transition_frontier.ml\", line 803, characters 12-66"
    "Called from file \"src/lib/transition_handler/processor.ml\", line 64, characters 17-51"
    "Called from file \"src/lib/transition_handler/processor.ml\", line 149, characters 8-129"
    "Called from file \"src/deferred0.ml\", line 56, characters 64-69"
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5"
    "Called from file \"src/job_queue.ml\", line 170, characters 6-47"
    "Caught by monitor coda"))
```

coda.log: https://gist.github.com/o1pranay/2579499710a710b1c6d9179c6bae2df2
registered_masks.dot: https://gist.github.com/o1pranay/b938a5a1dec7c1a852ef7741800ad14d
frontier.dot: https://gist.github.com/o1pranay/b47baf6b0c1f83cfe9217ffcff721cad

### PR DESCRIPTION
**Pull request by enolan**
See the commit messages for details. Adding the asserts make the unit tests fail, fixing up the child detection makes them pass again.

Checklist:

- [x] Tests were added for the new behavior 
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [x] Does this close issues? List them:

Closes #2969

### CODE REVIEW

**Comment by enolan** [comment]
oops, some of the staged ledger tests don't handle masks properly.

File: src/lib/merkle_mask/maskable_merkle_tree.ml [hunk 1]
```diff
@@ -142,14 +145,44 @@ module Make (Inputs : Inputs_intf) = struct
...
+      ~message:"parent in param should be parent in data structure"
+      ~expect:t_uuid
+      (Mask.Attached.get_parent mask |> get_uuid) ;
+    ( match grandchildren with
+    | `Check -> (
+      match Hashtbl.find registered_masks (Mask.Attached.get_uuid mask) with
+      | Some children ->
+          failwith @@ error_msg
+          @@ sprintf
+               !"it has children that must be unregistered first: %{sexp: \
```
Comment (psteckler) [inline src/lib/merkle_mask/maskable_merkle_tree.ml]: should this read "Mask has its own mask children..."

File: src/lib/merkle_mask/maskable_merkle_tree.ml [hunk 2]
```diff
@@ -142,14 +145,44 @@ module Make (Inputs : Inputs_intf) = struct
...
+                 Uuid.t list}"
+               (List.map ~f:Mask.Attached.get_uuid children)
+      | None ->
+          () )
+    | `I_promise_I_am_reparenting_this ->
```
Comment (psteckler) [inline src/lib/merkle_mask/maskable_merkle_tree.ml]: maybe "this" should be "descendants", to be clear ?

Comment (enolan) [reply src/lib/merkle_mask/maskable_merkle_tree.ml]: You pass it when you're unregistering a mask with a plan to immediately register it again with a different parent. Not when you are planning to reparent any children of the mask. I suppose both situations are possible, but the latter can be accomplished by reparenting the children first without having to shut off any checks.

Comment (psteckler) [reply src/lib/merkle_mask/maskable_merkle_tree.ml]: I see, you're using that when reparenting the children of the original mask.

OK, can I ask for "this_mask" instead of "this" ?

File: src/lib/merkle_mask/maskable_merkle_tree.ml [hunk 3]
```diff
@@ -142,14 +145,44 @@ module Make (Inputs : Inputs_intf) = struct
     Uuid.Table.add_multi registered_masks ~key:(get_uuid t) ~data:attached_mask ;
     attached_mask
 
-  let unregister_mask_exn (t : t) (mask : Mask.Attached.t) =
+  (* TODO We have the parent already from mask.parent. remove extra param. *)
```
Comment (nholland94) [inline src/lib/merkle_mask/maskable_merkle_tree.ml]: Does this TODO still need to be addressed before this PR lands? If not, either remove it if it isn't necessary anymore, or open and issue for it and add the number to this comment.
