### PR TITLE
long fork integration test

### LINKED ISSUE #2284: the consensus selection rule seems to be broken
While I am running the long fork integration test, I saw this suspicious log:
```json
{
  "timestamp": "2019-04-22 21:36:52.079901Z",
  "level": "Info",
  "source": {
    "module": "Consensus__Proof_of_stake",
    "location": "File \"src/lib/consensus/proof_of_stake.ml\", line 1925, characters 51-58"
  },
  "message": "selecting best consensus state",
  "metadata": {
    "candidate": {
      "length": "382",
      "epoch_length": "3",
      "min_length_of_epoch": "119",
      "last_vrf_output": "fWU6qmwioJTO3d0ZtHq3fqZp7mbqbaF/+Ts01TiAGyY=",
      "total_currency": 5004680,
      "curr_epoch": "3",
      "curr_slot": "16",
      "last_epoch_data": {
        "ledger": {
          "hash": "15652290550130430788618726384342739592920043987546874592829106168388911878120",
          "total_currency": 5003240
        },
        "seed": "28415498458656890090123013864478066866350772390518388240501477951229875447616",
        "start_checkpoint": "32146963520178768882393136347112638450785206767356683823239002892786424467294",
        "lock_checkpoint": "59016267513250053307331249537232862125453953388599213974348833073044304105746",
        "length": "126"
      },
      "curr_epoch_data": {
        "ledger": {
          "hash": "42039716627655665039558929385591830847445764016647666654340286681052313296751",
          "total_currency": 5004520
        },
        "seed": "107112017843519245865781682523810861409086798717297602078657880626991887173817",
        "start_checkpoint": "63776621853228401564692973272942858388717993237972227929769954779141246382125",
        "lock_checkpoint": "107112017843519245865781682523810861409086798717297602078657880626991887173817",
        "length": "16"
      },
      "has_ancestor_in_same_checkpoint_window": true,
      "checkpoints": {
        "data": {
          "prefix": [
            "108209262611525445785610203253803029622010368758842126551396217367969858578940"
          ],
          "tail": "0"
        },
        "hash": "59874423440196282904127479421504199920359553667367599728752860207046869452109"
      }
    },
    "existing": {
      "length": "1",
      "epoch_length": "0",
      "min_length_of_epoch": "144",
      "last_vrf_output": "z2h6/Rj/ToewON2up0Lpg8a2tYPYOIzIqOpm4VYy9sU=",
      "total_currency": 5001000,
      "curr_epoch": "0",
      "curr_slot": "0",
      "last_epoch_data": {
        "ledger": {
          "hash": "1678056473370721794947917208202817793106706428866741843524281314441623848529",
          "total_currency": 5001000
        },
        "seed": "107112017843519245865781682523810861409086798717297602078657880626991887173817",
        "start_checkpoint": "107112017843519245865781682523810861409086798717297602078657880626991887173817",
        "lock_checkpoint": "107112017843519245865781682523810861409086798717297602078657880626991887173817",
        "length": "1"
      },
      "curr_epoch_data": {
        "ledger": {
          "hash": "1678056473370721794947917208202817793106706428866741843524281314441623848529",
          "total_currency": 5001000
        },
        "seed": "107112017843519245865781682523810861409086798717297602078657880626991887173817",
        "start_checkpoint": "107112017843519245865781682523810861409086798717297602078657880626991887173817",
        "lock_checkpoint": "107112017843519245865781682523810861409086798717297602078657880626991887173817",
        "length": "2"
      },
      "has_ancestor_in_same_checkpoint_window": true,
      "checkpoints": {
        "data": {
          "prefix": [
            "108209262611525445785610203253803029622010368758842126551396217367969858578940"
          ],
          "tail": "0"
        },
        "hash": "59874423440196282904127479421504199920359553667367599728752860207046869452109"
      }
    },
    "host": "127.0.0.1",
    "pid": 20780,
    "port": 23002
  }
}
```
```json
{
  "timestamp": "2019-04-22 21:36:52.079976Z",
  "level": "Debug",
  "source": {
    "module": "Consensus__Proof_of_stake",
    "location": "File \"src/lib/consensus/proof_of_stake.ml\", line 1911, characters 54-61"
  },
  "message": "RESULT: Take -- (candidate current epoch lock checkpoint is equal to existing last epoch lock checkpoint) && (candidate is longer than existing)",
  "metadata": {
    "host": "127.0.0.1",
    "pid": 20780,
    "port": 23002
  }
}
```

### PR DESCRIPTION
**Pull request by ghost-not-in-the-shell**
In this PR, I created an integration test for bootstrap with long fork.

Closes #2284

### CODE REVIEW

File: src/app/cli/src/coda_long_fork.ml [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+  let snark_work_public_keys i =
+    Some
+      ( (List.nth_exn keypairs i).public_key
+      |> Signature_lib.Public_key.compress )
+  in
+  let%bind testnet =
+    Coda_worker_testnet.test logger n Option.some snark_work_public_keys
+      Protocols.Coda_pow.Work_selection.Seq ~max_concurrent_connections:None
+  in
+  let epoche_duration =
```
Comment (psteckler) [inline src/app/cli/src/coda_long_fork.ml]: `epoch_duration` ?

File: src/app/cli/src/coda_long_fork.ml [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+    Consensus.Constants.(block_window_duration_ms * 3 * c * k)
+  in
+  let%bind () =
+    Coda_worker_testnet.Restarts.restart_node testnet ~logger ~node:1
+      ~duration:(Time.Span.of_ms (2 * epoche_duration |> Float.of_int))
+  in
+  let%bind () = after (Time.Span.of_min 2.) in
```
Comment (psteckler) [inline src/app/cli/src/coda_long_fork.ml]: should the time here be a command-line option?
