### PR TITLE
We are not writing to closed pipes in syncable ledger

### LINKED ISSUE #1889: testnet - catchup crash - "write to closed pipe"
attempts to join at around block 50..

joins, seems to catchup and process a few blocks, then dies.

build: 0.1.62466-CI
sha: 30a3b29c434b87677786237f3c6b2ec4a0546fe0

```
(monitor.ml.Error
 ("write to closed pipe"
  (pipe
   ((id 12) (buffer ()) (size_budget 0) (pushback (Full ()))
    (num_values_read 0) (blocked_flushes ()) (blocked_reads ())
    (closed (Full ())) (read_closed (Full ()))
    (consumers
     (((pipe_id 12) (values_read Have_been_sent_downstream)
       (downstream_flushed <fun>))
      ((pipe_id 12) (values_read Have_been_sent_downstream)
       (downstream_flushed <fun>))))
    (upstream_flusheds ()))))
 ("Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30"
  "Called from file \"src/error.ml\", line 11, characters 19-40"
  "Called from file \"src/pipe.ml\", line 467, characters 2-15"
  "Called from file \"src/pipe.ml\" (inlined), line 473, characters 2-32"
  "Called from file \"lib/pipe_lib/strict_pipe.ml\", line 189, characters 21-50"
  "Called from file \"src/deferred0.ml\", line 61, characters 64-69"
  "Called from file \"src/job_queue.ml\" (inlined), line 120, characters 2-5"
  "Called from file \"src/job_queue.ml\", line 159, characters 6-47"
  "Caught by monitor coda"))
```

[2019-03-15-0348-catchup-fail-test1.tar.gz](https://github.com/CodaProtocol/coda/files/2969364/2019-03-15-0348-catchup-fail-test1.tar.gz)
[2019-03-15-0352-catchup-fail-test2.tar.gz](https://github.com/CodaProtocol/coda/files/2969365/2019-03-15-0352-catchup-fail-test2.tar.gz)

### PR DESCRIPTION
**Pull request by johnwu93**
Checklist:

- [ ] Tests were added for the new behavior
- [ ] All tests pass (CI will check this if you didn't)
- [ ] Serialized types are in stable-versioned modules
- [X] Does this close issues? List them:

Closes #1889

### CODE REVIEW

File: src/lib/syncable_ledger/syncable_ledger.ml [hunk 1]
```diff
@@ -486,16 +486,18 @@ end = struct
     in
     go (empty_hash_at_height start_height) hash start_height
 
+  let write_answer t answer =
+    don't_wait_for @@ Linear_pipe.write_if_open t.queries answer
```
Comment (cmr) [inline src/lib/syncable_ledger/syncable_ledger.ml]: use write_without_pushback_if_open. add it to `Linear_pipe` if you need.
