### PR TITLE
Use default if CODA_TIME_OFFSET undefined

### LINKED ISSUE #3336: Missing env vars don't fail gracefully
If we want to crash, I think we should

```ocaml
match get_env e with
| Some x -> x
| None ->
  eprintf "A nice message here";
  exit 1
```

### PR DESCRIPTION
**Pull request by psteckler**
Use default of 0 and log that fact if `CODA_TIME_OFFSET` is undefined.

Use `Core.Sys.getenv`, which returns an option, instead of `Unix.getenv`, which raises an exception, which we weren't handling.

Closes #3336.

### CODE REVIEW

File: src/lib/coda_base/block_time.ml [hunk 1]
```diff
@@ -43,18 +43,27 @@ module Time = struct
...
+    let basic ~logger =
       lazy
-        ( Core_kernel.Time.Span.of_int_sec @@ Int.of_string
-        @@ Unix.getenv "CODA_TIME_OFFSET" )
+        (let offset =
+           match Core.Sys.getenv "CODA_TIME_OFFSET" with
+           | Some tm ->
+               Int.of_string tm
+           | None ->
+               Logger.info logger ~module_:__MODULE__ ~location:__LOC__
```
Comment (bkase) [inline src/lib/coda_base/block_time.ml]: On further thinking, this should be a `debug` log as this will be printed whenever a user starts up their node during the normal usage

Comment (Schmavery) [reply src/lib/coda_base/block_time.ml]: During normal usage, isn't CODA_TIME_OFFSET not needed? seems like maybe in that case this code wouldn't be executed?

Comment (psteckler) [reply src/lib/coda_base/block_time.ml]: The log message appears only when `time_offsets` is in the config and the environment variable is not set.

I changed the code to use a `debug` message.
